"""B2's quality check: the self-made FP8 checkpoint against the bf16 original.

Two commands, both standard library only (they run on the GPU host, next to
the engine, where the port is bound to localhost):

    python quality.py generate --base-url URL --model NAME --out FILE.json
    python quality.py compare BF16.json FP8.json --out REPORT.md

``generate`` sends every prompt in ``quality_prompts.json`` greedily (temperature
0, a fixed ``max_tokens``) and records the replies. ``compare`` scores both
files: accuracy on the ``exact`` items (the reply contains the expected answer)
and, for every item, whether the two models' replies are identical and how long
their common prefix is. It writes a markdown report whose figures all come
from the two files. This is a smoke-level check on a small fixed set, not an
eval: a real rollout would gate on a proper eval suite.
"""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path

PROMPTS = Path(__file__).with_name("quality_prompts.json")
MAX_TOKENS = 128


def chat(base_url: str, model: str, prompt: str) -> str:
    body = json.dumps(
        {
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": MAX_TOKENS,
            "temperature": 0,
        }
    ).encode()
    req = urllib.request.Request(  # noqa: S310 - operator-given local engine URL
        base_url.rstrip("/") + "/v1/chat/completions",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=120) as resp:  # noqa: S310 - as above
        return json.load(resp)["choices"][0]["message"]["content"]


def generate(args: argparse.Namespace) -> None:
    prompts = json.loads(PROMPTS.read_text())
    out = {
        "model": args.model,
        "max_tokens": MAX_TOKENS,
        "exact": [
            {**item, "reply": chat(args.base_url, args.model, item["q"])}
            for item in prompts["exact"]
        ],
        "open": [
            {"q": q, "reply": chat(args.base_url, args.model, q)}
            for q in prompts["open"]
        ],
    }
    Path(args.out).write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {args.out}")


def correct(item: dict) -> bool:
    return item["a"].lower() in item["reply"].lower()


def common_prefix(a: str, b: str) -> int:
    n = 0
    for x, y in zip(a, b, strict=False):
        if x != y:
            break
        n += 1
    return n


def compare(args: argparse.Namespace) -> None:
    ref, cand = (json.loads(Path(p).read_text()) for p in (args.ref, args.cand))
    pairs = [
        (r, c)
        for kind in ("exact", "open")
        for r, c in zip(ref[kind], cand[kind], strict=True)
    ]
    exact_ref = sum(correct(i) for i in ref["exact"])
    exact_cand = sum(correct(i) for i in cand["exact"])
    n_exact = len(ref["exact"])
    identical = sum(r["reply"] == c["reply"] for r, c in pairs)
    prefix = [
        common_prefix(r["reply"], c["reply"]) / max(len(r["reply"]), 1)
        for r, c in pairs
    ]
    changed = [
        (r, c)
        for r, c in zip(ref["exact"], cand["exact"], strict=True)
        if correct(r) != correct(c)
    ]
    lines = [
        "# B2 quality check",
        "",
        (
            f"Generated by `quality.py compare {args.ref} {args.cand}`. "
            f"Greedy, `max_tokens` {ref['max_tokens']}."
        ),
        "",
        "| | reference | candidate |",
        "|---|---|---|",
        f"| Model | `{ref['model']}` | `{cand['model']}` |",
        (
            f"| Exact-answer items correct | {exact_ref} / {n_exact} "
            f"| {exact_cand} / {n_exact} |"
        ),
        "",
        f"- Replies identical to the reference: {identical} / {len(pairs)}.",
        (
            "- Mean common prefix, as a fraction of the reference reply: "
            f"{sum(prefix) / len(prefix):.3f}."
        ),
        f"- Exact-answer items whose correctness changed: {len(changed)}.",
    ]
    lines += [
        f"  - {r['q']!r}: expected {r['a']!r}; reference {r['reply']!r} "
        f"-> candidate {c['reply']!r}"
        for r, c in changed
    ]
    Path(args.out).write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate")
    g.add_argument("--base-url", default="http://127.0.0.1:8000")
    g.add_argument("--model", required=True)
    g.add_argument("--out", required=True)
    c = sub.add_parser("compare")
    c.add_argument("ref")
    c.add_argument("cand")
    c.add_argument("--out", required=True)
    args = p.parse_args()
    (generate if args.cmd == "generate" else compare)(args)


if __name__ == "__main__":
    main()
