package report

import (
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strings"
)

// Marker lines. A generated block is everything between a begin line and
// the end line with the same id; each is a whole line on its own.
const (
	markerOpen  = "<!-- bench-report:"
	markerClose = " -->"
)

// BeginMarker and EndMarker are the marker lines for an id, without the
// newline.
func BeginMarker(id string) string { return markerOpen + "begin " + id + markerClose }

// EndMarker is BeginMarker's closing twin.
func EndMarker(id string) string { return markerOpen + "end " + id + markerClose }

// parseMarker recognises a marker line (its newline already trimmed).
func parseMarker(line string) (kind, id string, ok bool) {
	rest, found := strings.CutPrefix(line, markerOpen)
	if !found {
		return "", "", false
	}
	rest, found = strings.CutSuffix(rest, markerClose)
	if !found {
		return "", "", false
	}
	kind, id, found = strings.Cut(rest, " ")
	if !found || (kind != "begin" && kind != "end") || id == "" || strings.ContainsAny(id, " \t") {
		return "", "", false
	}
	return kind, id, true
}

// Rewrite replaces the body of every marker block in doc with render(id)
// and returns the new document and the ids in document order. Every byte
// outside the blocks, the marker lines included, is kept as it is, so
// hand-written prose is never touched. An unmatched, nested or mismatched
// marker is an error, and so is a render error: nothing is half-written.
func Rewrite(doc []byte, render func(id string) ([]byte, error)) (out []byte, ids []string, err error) {
	var buf bytes.Buffer
	open := "" // id of the block being skipped
	lineNo := 0
	for rest := doc; len(rest) > 0; {
		lineNo++
		line := rest
		if i := bytes.IndexByte(rest, '\n'); i >= 0 {
			line = rest[:i+1]
		}
		rest = rest[len(line):]
		kind, id, isMarker := parseMarker(strings.TrimRight(string(line), "\r\n"))
		switch {
		case !isMarker && open != "":
			continue // old generated content: dropped
		case !isMarker:
			buf.Write(line)
		case kind == "begin" && open != "":
			return nil, nil, fmt.Errorf("line %d: begin %s inside block %s", lineNo, id, open)
		case kind == "begin":
			buf.Write(line)
			if !bytes.HasSuffix(line, []byte("\n")) {
				return nil, nil, fmt.Errorf("line %d: block %s has no end marker", lineNo, id)
			}
			body, rerr := render(id)
			if rerr != nil {
				return nil, nil, fmt.Errorf("line %d: %s: %w", lineNo, id, rerr)
			}
			buf.Write(body)
			open = id
			ids = append(ids, id)
		case open == "":
			return nil, nil, fmt.Errorf("line %d: end %s without a begin", lineNo, id)
		case id != open:
			return nil, nil, fmt.Errorf("line %d: end %s closes block %s", lineNo, id, open)
		default:
			buf.Write(line)
			open = ""
		}
	}
	if open != "" {
		return nil, nil, fmt.Errorf("block %s has no end marker", open)
	}
	return buf.Bytes(), ids, nil
}

// Block ids.
const (
	kindSLO      = "slo"
	kindTable    = "table"
	kindEngine   = "engine"
	kindCompare  = "compare"
	kindHeadline = "headline"
)

// Doc is everything a block can be rendered from.
type Doc struct {
	// Command is the `bench report` command line, printed at the top of
	// every block so it says how it was made.
	Command string
	SLOPath string
	SLO     SLO
	Runs    []Run
	Tables  []Table // Tables[i] is Runs[i] judged
}

// errUnknownBlock marks an id this version cannot render.
var errUnknownBlock = errors.New("unknown block (want slo, table:<run-id>, engine:<run-id>, compare:<experiment-run-id>:<baseline-run-id> or headline:<profile>)")

// Render renders the body of one block: a provenance line, then the
// content, framed by blank lines so Markdown sees the tables as blocks.
func (d *Doc) Render(id string) ([]byte, error) {
	parts := strings.Split(id, ":")
	var body string
	var inputs []string
	var err error
	switch {
	case len(parts) == 1 && parts[0] == kindSLO:
		body, inputs = SLOMarkdown(&d.SLO), []string{d.SLOPath}
	case len(parts) == 2 && (parts[0] == kindTable || parts[0] == kindEngine):
		i, e := d.run(parts[1])
		if e != nil {
			return nil, e
		}
		inputs = []string{d.Runs[i].Dir}
		if parts[0] == kindTable {
			body = TableMarkdown(&d.Tables[i])
			inputs = append(inputs, d.SLOPath)
		} else {
			body = EngineMarkdown(&d.Tables[i])
		}
	case len(parts) == 3 && parts[0] == kindCompare:
		body, inputs, err = d.compare(parts[1], parts[2])
	case len(parts) == 2 && parts[0] == kindHeadline:
		body, inputs, err = d.headline(parts[1])
	default:
		err = errUnknownBlock
	}
	if err != nil {
		return nil, err
	}
	head := fmt.Sprintf("<!-- Generated by `%s` from %s. Edit outside the markers only. -->\n\n",
		d.Command, strings.Join(inputs, ", "))
	return []byte(head + body + "\n"), nil
}

func (d *Doc) run(id string) (int, error) {
	for i := range d.Runs {
		if d.Runs[i].ID() == id {
			return i, nil
		}
	}
	return 0, fmt.Errorf("run %s is not among the run directories given", id)
}

func (d *Doc) compare(expID, baseID string) (body string, inputs []string, err error) {
	ei, err := d.run(expID)
	if err != nil {
		return "", nil, err
	}
	bi, err := d.run(baseID)
	if err != nil {
		return "", nil, err
	}
	c, err := Compare(&d.Tables[ei], &d.Tables[bi])
	if err != nil {
		return "", nil, err
	}
	return CompareMarkdown(&c), []string{d.Runs[ei].Dir, d.Runs[bi].Dir, d.SLOPath}, nil
}

func (d *Doc) headline(profile string) (body string, inputs []string, err error) {
	var hs []Headline
	var tables []*Table
	for i := range d.Tables {
		if d.Tables[i].Profile == profile {
			hs = append(hs, MaxCompliant(&d.Tables[i]))
			tables = append(tables, &d.Tables[i])
			inputs = append(inputs, d.Runs[i].Dir)
		}
	}
	if len(hs) == 0 {
		return "", nil, fmt.Errorf("no run of profile %q among the run directories given", profile)
	}
	return HeadlineMarkdown(tables, hs), append(inputs, d.SLOPath), nil
}

// Skeleton is a new results document with a block for every run: the SLO,
// then per profile its headline and each run's tables, with a comparison
// against the profile's first baseline run (engine config "baseline") for
// every other run. Prose goes between the blocks.
func (d *Doc) Skeleton() []byte {
	var b strings.Builder
	block := func(id string) { b.WriteString(BeginMarker(id) + "\n" + EndMarker(id) + "\n\n") }
	b.WriteString("# Results\n\nGenerated tables are between `bench-report` markers; `bench report` rewrites only those.\n\n## SLO\n\n")
	block(kindSLO)
	var profiles []string
	for i := range d.Runs {
		if p := d.Runs[i].Profile(); !slices.Contains(profiles, p) {
			profiles = append(profiles, p)
		}
	}
	for _, p := range profiles {
		b.WriteString("## " + p + "\n\n")
		block(kindHeadline + ":" + p)
		base := ""
		for i := range d.Runs {
			if r := &d.Runs[i]; r.Profile() == p && base == "" && r.Config.Engine.Config == "baseline" {
				base = r.ID()
			}
		}
		for i := range d.Runs {
			r := &d.Runs[i]
			if r.Profile() != p {
				continue
			}
			b.WriteString("### " + r.ID() + "\n\n")
			block(kindTable + ":" + r.ID())
			block(kindEngine + ":" + r.ID())
			if base != "" && r.ID() != base {
				block(kindCompare + ":" + r.ID() + ":" + base)
			}
		}
	}
	return []byte(strings.TrimSuffix(b.String(), "\n"))
}

// MissingTables lists the runs given with no table block in ids, for a
// hint to add one: a run passed to the command but shown nowhere.
func (d *Doc) MissingTables(ids []string) []string {
	var out []string
	for i := range d.Runs {
		if !slices.Contains(ids, kindTable+":"+d.Runs[i].ID()) {
			out = append(out, d.Runs[i].ID())
		}
	}
	return out
}
