package report

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Regenerate the golden file with `go test ./internal/report -update` and
// review the diff.
var update = flag.Bool("update", false, "rewrite testdata/*.golden")

const (
	baseID = "interactive-baseline-20260101-000000"
	expID  = "interactive-batching-20260101-010000"
	tpID   = "throughput-baseline-20260101-020000"
)

// testDoc is a small document's inputs: an interactive baseline passing at
// c=1 and 2 and failing at 4 on both bounds, an experiment that runs 2, 4
// and 8 and passes at 4, and a throughput baseline.
func testDoc(t *testing.T) *Doc {
	t.Helper()
	runs := []Run{
		newRun(baseID, "interactive", "baseline", lvl(1, 100, 18.4, 9.5), lvl(2, 200, 32, 9.7), lvl(4, 380, 117.1, 26.3)),
		newRun(expID, "interactive", "batching", lvl(2, 210, 30, 9.6), lvl(4, 400, 90, 24.9), lvl(8, 600, 150, 30)),
		newRun(tpID, "throughput", "baseline", lvl(8, 600, 200, 13)),
	}
	d := &Doc{Command: "bench report --out docs/03-results.md results/a results/b results/c", SLOPath: "docs/slo.json", SLO: testSLO, Runs: runs}
	for i := range runs {
		tab, err := NewTable(&runs[i], &testSLO, 0.9)
		if err != nil {
			t.Fatal(err)
		}
		d.Tables = append(d.Tables, tab)
	}
	return d
}

// The skeleton, filled, pins the whole generated document byte for byte:
// every block kind, the comparison with levels on one side only, and the
// headline's next-level note.
func TestSkeletonFilledMatchesGolden(t *testing.T) {
	t.Parallel()
	d := testDoc(t)
	got, ids, err := Rewrite(d.Skeleton(), d.Render)
	if err != nil {
		t.Fatal(err)
	}
	wantIDs := "slo,headline:interactive,table:" + baseID + ",engine:" + baseID +
		",table:" + expID + ",engine:" + expID + ",compare:" + expID + ":" + baseID +
		",headline:throughput,table:" + tpID + ",engine:" + tpID
	if strings.Join(ids, ",") != wantIDs {
		t.Errorf("skeleton blocks = %v\nwant %s", ids, wantIDs)
	}
	path := filepath.Join("testdata", "report.md.golden")
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("generated document differs from %s; rerun with -update and review the diff:\n%s", path, got)
	}
	// Deterministic: the same inputs give the same bytes, and a second
	// pass over the output changes nothing.
	again, _, err := Rewrite(got, testDoc(t).Render)
	if err != nil || !bytes.Equal(again, got) {
		t.Errorf("second pass differs (%v)", err)
	}
}

func TestEveryBlockStartsWithTheCommandAndItsInputs(t *testing.T) {
	t.Parallel()
	d := testDoc(t)
	tests := []struct{ id, inputs string }{
		{"slo", "docs/slo.json"},
		{"table:" + baseID, "results/" + baseID + ", docs/slo.json"},
		{"engine:" + baseID, "results/" + baseID},
		{"compare:" + expID + ":" + baseID, "results/" + expID + ", results/" + baseID + ", docs/slo.json"},
		{"headline:interactive", "results/" + baseID + ", results/" + expID + ", docs/slo.json"},
	}
	for _, tt := range tests {
		b, err := d.Render(tt.id)
		if err != nil {
			t.Fatal(err)
		}
		first, _, _ := strings.Cut(string(b), "\n")
		want := "<!-- Generated by `" + d.Command + "` from " + tt.inputs + ". Edit outside the markers only. -->"
		if first != want {
			t.Errorf("%s first line = %q\nwant %q", tt.id, first, want)
		}
	}
}

func TestFormatting(t *testing.T) {
	t.Parallel()
	tests := []struct{ got, want string }{
		{Pct(4.95), "+5.0%"}, // 4.95 is 4.9500000000000002 in binary: rounds up
		{Pct(-27.04), "-27.0%"},
		{Pct(-0.04), "+0.0%"}, // rounds to zero: no "-0.0"
		{Pct(0), "+0.0%"},
		{Latency(MetricTTFT, 117.12), "117.1 ms"},
		{Latency(MetricTPOT, 9.54), "9.5 ms"},
		{Latency(MetricE2E, 12992.6), "12.99 s"},
		{latencyBare(MetricE2E, 12992.6), "12.99"},
		{latencyBare(MetricTTFT, 18.43), "18.4"},
		{(&Bound{MetricE2E, 95, 15000}).Limit(), "E2E p95 ≤ 15 s"},
		{(&Bound{MetricTTFT, 99, 150}).Limit(), "TTFT p99 ≤ 150 ms"},
		{(&Bound{MetricTPOT, 50, 12.5}).Limit(), "TPOT p50 ≤ 12.5 ms"},
		{row("a|b", "c"), `| a\|b | c |` + "\n"},
		{header(2, "a", "b", "c"), "| a | b | c |\n|---|---|---:|\n"},
	}
	for _, tt := range tests {
		if tt.got != tt.want {
			t.Errorf("got %q, want %q", tt.got, tt.want)
		}
	}
}

func TestNextCellSaysWhyTheLevelAboveDoesNotCarryTheHeadline(t *testing.T) {
	t.Parallel()
	fail := lr(8, 500, false, false)
	fail.Level.Errors = 2
	fail.Bounds = []BoundResult{
		{Bound: Bound{MetricTTFT, 95, 100}, HasData: true, Value: 125, Pass: false, MarginPct: 25},
		{Bound: Bound{MetricTPOT, 95, 25}, HasData: true, Value: 10, Pass: true, MarginPct: -60},
	}
	best, meets := lr(4, 300, true, true), lr(8, 300, true, true)
	tests := []struct {
		name string
		h    Headline
		want string
	}{
		{"None", Headline{}, "–"},
		{"Top", Headline{Found: true, Best: &best}, "none: the headline is the top of the sweep"},
		{"Meets", Headline{Found: true, Best: &best, Next: &meets}, "c=8, 300.0 tok/s: meets the SLO with no more output"},
		{"Fails", Headline{Found: true, Best: &best, Next: &fail}, "c=8, 500.0 tok/s: fails TTFT p95 125.0 ms (+25.0%), 2 errors, engine check CACHED"},
	}
	for _, tt := range tests {
		if got := nextCell(&tt.h); got != tt.want {
			t.Errorf("%s: nextCell = %q, want %q", tt.name, got, tt.want)
		}
	}
}
