package chart

import (
	"bytes"
	"encoding/xml"
	"errors"
	"flag"
	"io"
	"math"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite testdata/*.golden")

func TestNiceTicksStepsOneTwoTwoPointFiveOrFiveTimesAPowerOfTen(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name  string
		top   float64
		ticks []float64
		step  float64
	}{
		// raw = 100/4 = 25; 2.5 × 10 = 25 ≥ 25, so step 25 and 4 steps.
		{"percent axis", 100, []float64{0, 25, 50, 75, 100}, 25},
		// raw = 4471.2/4 = 1117.8; 1 × 1000 < 1117.8 ≤ 2 × 1000.
		{"interactive tok/s", 4471.2, []float64{0, 2000, 4000, 6000}, 2000},
		// raw = 0.225; 2.5 × 0.1 = 0.25 ≥ 0.225; ceil(0.9/0.25) = 4.
		{"fractional", 0.9, []float64{0, 0.25, 0.5, 0.75, 1}, 0.25},
		// raw = 30/4 = 7.5; 5 × 1 < 7.5 ≤ 10 × 1: no multiplier fits, so 10.
		{"falls through to ten", 30, []float64{0, 10, 20, 30}, 10},
		{"empty axis", 0, []float64{0, 1}, 1},
		{"not a number", math.NaN(), []float64{0, 1}, 1},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Parallel()
			ticks, step := niceTicks(c.top)
			if step != c.step || len(ticks) != len(c.ticks) {
				t.Fatalf("niceTicks(%g) = %v step %g, want %v step %g", c.top, ticks, step, c.ticks, c.step)
			}
			for i := range ticks {
				if math.Abs(ticks[i]-c.ticks[i]) > 1e-9 {
					t.Fatalf("niceTicks(%g) = %v, want %v", c.top, ticks, c.ticks)
				}
			}
		})
	}
}

func TestTickLabelUsesTheDecimalsItsStepNeeds(t *testing.T) {
	t.Parallel()
	cases := []struct {
		v, step float64
		want    string
	}{
		{2000, 2000, "2,000"},
		{2.5, 2.5, "2.5"},
		{7.5, 2.5, "7.5"},
		{0.25, 0.25, "0.25"},
		{0, 0.25, "0.00"},
		{50, 50, "50"},
	}
	for _, c := range cases {
		if got := tickLabel(c.v, c.step); got != c.want {
			t.Errorf("tickLabel(%g, %g) = %q, want %q", c.v, c.step, got, c.want)
		}
	}
}

func TestCommasGroupsThousandsAndKeepsSignAndDecimals(t *testing.T) {
	t.Parallel()
	cases := []struct {
		v    float64
		d    int
		want string
	}{
		{4140.1, 0, "4,140"},
		{6897.6, 0, "6,898"},
		{1234567.891, 2, "1,234,567.89"},
		{-1234, 0, "-1,234"},
		{999, 0, "999"},
		{1000, 1, "1,000.0"},
	}
	for _, c := range cases {
		if got := Commas(c.v, c.d); got != c.want {
			t.Errorf("Commas(%g, %d) = %q, want %q", c.v, c.d, got, c.want)
		}
	}
}

func TestNumDropsTrailingZerosAndNegativeZero(t *testing.T) {
	t.Parallel()
	for v, want := range map[float64]string{3: "3", 12.34: "12.3", -0.04: "0", -2.5: "-2.5"} {
		if got := num(v); got != want {
			t.Errorf("num(%g) = %q, want %q", v, got, want)
		}
	}
}

func TestLog2AxisSpacesDoublingsEquallyInsideThePadding(t *testing.T) {
	t.Parallel()
	a := newLog2Axis(1, 256, 100, 900)
	step := a.at(2) - a.at(1)
	if d := a.at(256) - a.at(128); math.Abs(d-step) > 1e-9 {
		t.Errorf("doubling 1→2 is %g px, 128→256 is %g px; a log scale spaces them equally", step, d)
	}
	if a.at(1) <= 100 || a.at(256) >= 900 {
		t.Errorf("ends at %g and %g, want inside (100, 900) for the padding", a.at(1), a.at(256))
	}
	one := newLog2Axis(8, 8, 0, 100)
	if x := one.at(8); math.Abs(x-50) > 1e-9 {
		t.Errorf("a one-level axis puts it at %g, want the middle (50)", x)
	}
}

func TestLinearScaleRunsUpwardFromTheBaseline(t *testing.T) {
	t.Parallel()
	s := linear{max: 200, y0: 300, y1: 100}
	if s.at(0) != 300 || s.at(200) != 100 || s.at(100) != 200 {
		t.Errorf("at(0, 100, 200) = %g, %g, %g, want 300, 200, 100", s.at(0), s.at(100), s.at(200))
	}
}

func TestSkipsTickFindsALevelStrictlyBetween(t *testing.T) {
	t.Parallel()
	ticks := []float64{1, 2, 4, 8}
	if !skipsTick(1, 4, ticks) {
		t.Error("1 → 4 skips 2")
	}
	if skipsTick(2, 4, ticks) || skipsTick(4, 4, ticks) {
		t.Error("2 → 4 and 4 → 4 skip nothing")
	}
}

// sample is a small two-series, two-panel chart: the reference runs every
// level; the experiment skips 2 and 4 and misses the SLO at 8.
func sample() Lines {
	ref := Series{Name: "ref", Slot: 0, Points: []Point{
		{X: 1, Y: 100, Filled: true, Tip: "ref 1"}, {X: 2, Y: 190, Filled: true}, {X: 4, Y: 350, Filled: true}, {X: 8, Y: 400},
	}}
	exp := Series{Name: "exp <B&C>", Slot: 1, Points: []Point{
		{X: 8, Y: 700}, {X: 1, Y: 120, Filled: true},
	}}
	return Lines{
		Title:    "Sample & title",
		Subtitle: []string{"one", "two"},
		Source:   "Generated by `bench chart --kind latency`",
		XTitle:   "Concurrency",
		XTicks:   []float64{1, 2, 4, 8},
		Key:      true,
		Panels: []Panel{
			{Title: "Output", Series: []Series{ref, exp}, Callouts: []Callout{{X: 4, Y: 350, Text: "350 at c=4"}}},
			{Title: "TTFT", Series: []Series{ref}, Limit: &Limit{Value: 300, Label: "SLO ≤ 300 ms"}, Max: 0},
		},
		Notes: []string{"a note"},
	}
}

func golden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join("testdata", name)
	if *update {
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s differs from the golden file; run go test ./internal/chart -update and review the diff", name)
	}
}

// wellFormed parses the whole document as XML.
func wellFormed(t *testing.T, svg []byte) {
	t.Helper()
	dec := xml.NewDecoder(bytes.NewReader(svg))
	for {
		_, err := dec.Token()
		if errors.Is(err, io.EOF) {
			return
		}
		if err != nil {
			t.Fatalf("not well-formed XML: %v", err)
		}
	}
}

func TestLinesRendersTheGoldenSVG(t *testing.T) {
	t.Parallel()
	c := sample()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	wellFormed(t, got)
	golden(t, "lines.svg.golden", got)
}

func TestLinesEscapesTextAndRecordsTheSourceInMetadata(t *testing.T) {
	t.Parallel()
	c := sample()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	for _, want := range []string{
		"exp &lt;B&amp;C&gt;", "<title>Sample &amp; title</title>",
		"<metadata>Generated by `bench chart --kind latency`</metadata>",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("output lacks %q", want)
		}
	}
	if strings.Contains(s, "<!--") {
		t.Error("output has an XML comment; the command's -- is illegal there, which is why it goes in <metadata>")
	}
}

// pathsOf returns the d attribute of every series line of a slot.
func pathsOf(svg, slot string) []string {
	var out []string
	for _, line := range strings.Split(svg, "\n") {
		if strings.Contains(line, `class="ln l`+slot+`"`) && strings.HasPrefix(line, `<path d="`) {
			d, _, _ := strings.Cut(strings.TrimPrefix(line, `<path d="`), `"`)
			out = append(out, d)
		}
	}
	return out
}

func TestLinesBreakWhereASeriesSkipsALevel(t *testing.T) {
	t.Parallel()
	c := sample()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	// The experiment has levels 1 and 8 only; 2 and 4 lie between, so no
	// segment joins them and no line is drawn. Its one path is the legend
	// key, a horizontal stroke (H).
	for _, d := range pathsOf(string(got), "1") {
		if strings.Contains(d, "L") {
			t.Errorf("a segment joins levels with unrun levels between them: %q", d)
		}
	}
	// The reference runs every level: one continuous line per panel.
	for _, d := range pathsOf(string(got), "0")[1:] {
		if strings.Count(d, "M") != 1 || strings.Count(d, "L") != 3 {
			t.Errorf("reference line %q, want one move and three segments", d)
		}
	}
}

func TestLinesMarkFailingLevelsHollow(t *testing.T) {
	t.Parallel()
	c := sample()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	// ref: three filled data points in each of two panels, plus the legend
	// key and the "meets SLO" key (both slot 0); exp: one filled point
	// plus its legend key.
	if n := strings.Count(s, `class="mk m0"`); n != 3*2+2 {
		t.Errorf("%d filled slot-0 markers, want 8", n)
	}
	if n := strings.Count(s, `class="ho h0"`); n != 2+1 {
		t.Errorf("%d hollow slot-0 markers, want 3 (c=8 in both panels, the key)", n)
	}
	if n := strings.Count(s, `class="ho h1"`); n != 1 {
		t.Errorf("%d hollow slot-1 markers, want 1", n)
	}
}

func TestPanelMaxFixesTheAxis(t *testing.T) {
	t.Parallel()
	c := Lines{XTicks: []float64{1, 2}, Panels: []Panel{{
		Title: "KV", Max: 100,
		Series: []Series{{Name: "s", Points: []Point{{X: 1, Y: 97}, {X: 2, Y: 98}}}},
	}}}
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	// Sized to the data (98 × 1.08) the axis would reach 150; fixed, it stops at 100.
	if strings.Contains(string(got), ">150</text>") || !strings.Contains(string(got), ">100</text>") {
		t.Error("the axis is not fixed at 100")
	}
}

func TestCalloutsThatWouldCollideGoBelowThePoint(t *testing.T) {
	t.Parallel()
	d := newDoc(width, 400, "t", "d", "s")
	xs := newLog2Axis(1, 8, plotLeft, plotRight)
	ys := linear{max: 100, y0: 300, y1: 100}
	d.callouts([]Callout{{X: 2, Y: 50, Text: "first label"}, {X: 2, Y: 50, Text: "second"}}, xs, ys)
	var ys2 []string
	for _, line := range strings.Split(d.b.String(), "\n") {
		if strings.Contains(line, `class="v halo"`) {
			_, rest, _ := strings.Cut(line, ` y="`)
			y, _, _ := strings.Cut(rest, `"`)
			ys2 = append(ys2, y)
		}
	}
	// The point is at y = 200: the first label sits above (baseline 200 −
	// 10 − 2 = 188), the second below (200 + 24 − 2 = 222).
	if !slices.Equal(ys2, []string{"188", "222"}) {
		t.Errorf("callout baselines %v, want [188 222]", ys2)
	}
}

func TestLinesRejectsWhatItCannotDraw(t *testing.T) {
	t.Parallel()
	cases := map[string]func(*Lines){
		"no panels":   func(c *Lines) { c.Panels = nil },
		"no ticks":    func(c *Lines) { c.XTicks = nil },
		"zero tick":   func(c *Lines) { c.XTicks = []float64{0, 1} },
		"bad slot":    func(c *Lines) { c.Panels[0].Series[0].Slot = Slots },
		"NaN point":   func(c *Lines) { c.Panels[0].Series[0].Points[0].Y = math.NaN() },
		"zero x":      func(c *Lines) { c.Panels[0].Series[0].Points[0].X = 0 },
		"infinite y":  func(c *Lines) { c.Panels[1].Series[0].Points[1].Y = math.Inf(1) },
		"slot below0": func(c *Lines) { c.Panels[0].Series[1].Slot = -1 },
	}
	for name, mutate := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			c := sample()
			c.Panels = slices.Clone(c.Panels)
			for i := range c.Panels {
				c.Panels[i].Series = slices.Clone(c.Panels[i].Series)
				for j := range c.Panels[i].Series {
					c.Panels[i].Series[j].Points = slices.Clone(c.Panels[i].Series[j].Points)
				}
			}
			mutate(&c)
			if _, err := c.SVG(); err == nil {
				t.Error("SVG() accepted it")
			}
		})
	}
}

func sampleBars() Bars {
	return Bars{
		Title:    "Headline",
		Subtitle: []string{"sub"},
		Source:   "src",
		Groups: []BarGroup{
			{Title: "Interactive", Bars: []Bar{
				{Name: "Baseline", Slot: 0, Value: 4140.1, Label: "4,140 tok/s at c=64"},
				{Name: "B2", Slot: 1, Value: 6897.6, Label: "6,898 tok/s at c=128 (+66.6%)"},
			}},
			{Title: "Throughput", Bars: []Bar{
				{Name: "Baseline", Slot: 0, Value: 1583.9, Label: "1,584 tok/s at c=64"},
				{Name: "B1", Slot: 2, Missing: true, Label: "no level meets the SLO"},
			}},
		},
		Notes: []string{"note"},
	}
}

func TestBarsRendersTheGoldenSVG(t *testing.T) {
	t.Parallel()
	c := sampleBars()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	wellFormed(t, got)
	golden(t, "bars.svg.golden", got)
}

func TestBarsScaleEachGroupToItsLongestBarAndDrawNoBarWhenMissing(t *testing.T) {
	t.Parallel()
	c := sampleBars()
	got, err := c.SVG()
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	// Three drawn bars (b0, b1, b0); the missing B1 has only its label.
	if n := strings.Count(s, `class="b0"`) + strings.Count(s, `class="b1"`) + strings.Count(s, `class="b2"`); n != 3 {
		t.Errorf("%d bars drawn, want 3", n)
	}
	if !strings.Contains(s, "no level meets the SLO") {
		t.Error("the missing bar's label is not drawn")
	}
	// The longest bar in each group ends at the same x: each group has
	// its own scale.
	var ends []string
	for _, line := range strings.Split(s, "\n") {
		if strings.HasPrefix(line, `<path d="M`) && strings.Contains(line, `class="b`) {
			_, rest, _ := strings.Cut(line, "A4 4 0 0 1 ")
			x, _, _ := strings.Cut(rest, " ")
			ends = append(ends, x)
		}
	}
	if len(ends) != 3 || ends[1] != ends[2] {
		t.Errorf("bar ends %v: the B2 bar (group 1) and the throughput baseline (group 2) should both reach the group maximum", ends)
	}
}

func TestBarsRejectWhatTheyCannotDraw(t *testing.T) {
	t.Parallel()
	cases := map[string]Bars{
		"no groups":      {},
		"empty group":    {Groups: []BarGroup{{Title: "g"}}},
		"bad slot":       {Groups: []BarGroup{{Bars: []Bar{{Name: "b", Slot: 9}}}}},
		"negative value": {Groups: []BarGroup{{Bars: []Bar{{Name: "b", Value: -1}}}}},
		"NaN value":      {Groups: []BarGroup{{Bars: []Bar{{Name: "b", Value: math.NaN()}}}}},
	}
	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if _, err := c.SVG(); err == nil {
				t.Error("SVG() accepted it")
			}
		})
	}
}

func TestStylesheetSwitchesEveryColorInDarkMode(t *testing.T) {
	t.Parallel()
	s := stylesheet()
	light, dark, ok := strings.Cut(s, "@media (prefers-color-scheme:dark){")
	if !ok {
		t.Fatal("no dark-mode block")
	}
	for _, tok := range tokens {
		if !strings.Contains(light, tok.light) {
			t.Errorf("light rules lack %s %s", tok.name, tok.light)
		}
		if !strings.Contains(dark, tok.dark) {
			t.Errorf("dark rules lack %s %s", tok.name, tok.dark)
		}
	}
	if strings.Contains(s, "var(") {
		t.Error("the stylesheet uses CSS custom properties, which SVG rasterizers ignore")
	}
}
