// Package chart renders the benchmark's figures as static SVG: stacked line
// panels over a log₂ concurrency axis, and horizontal bars. It knows nothing
// about runs or SLOs; cmd/bench builds the series from report tables, so a
// chart can never disagree with the docs/03 tables it sits beside.
//
// The output is deterministic (fixed float formatting, no map iteration), so
// a committed SVG can be regenerated byte for byte from the command recorded
// in its <metadata>. Colors are CSS custom properties with a
// prefers-color-scheme block, so one file reads on light and dark pages.
// Palette and mark specs follow the house data-viz method: 2px lines, r=4
// markers with a 2px surface ring, 4px rounded bar ends, hairline solid grid,
// text in ink tokens, never in a series color.
package chart

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"strconv"
	"strings"
)

// Slots is the number of series colors: slot 0 is the reference (secondary
// ink, for the baseline) and slots 1–3 are categorical hues. The three hues
// pass the palette validator on all pairs in both modes; aqua (slot 3) is
// under 3:1 on the light surface, so every chart carries a legend and the
// docs/03 tables are its table view.
const Slots = 4

// tokens are the palette's light and dark values. The stylesheet writes
// plain colors per class, not CSS custom properties, which many SVG
// rasterizers (and so slide tools) do not support; a renderer that ignores
// the media query falls back to light.
var tokens = []struct{ name, light, dark string }{
	{"surface", "#fcfcfb", "#1a1a19"},
	{"ink1", "#0b0b0b", "#ffffff"},
	{"ink2", "#52514e", "#c3c2b7"},
	{"muted", "#898781", "#898781"},
	{"grid", "#e1e0d9", "#2c2c2a"},
	{"axis", "#c3c2b7", "#383835"},
	{"s0", "#52514e", "#c3c2b7"},
	{"s1", "#2a78d6", "#3987e5"},
	{"s2", "#eb6834", "#d95926"},
	{"s3", "#1baf7a", "#199e70"},
}

// colorRules maps each class to the property and token it takes.
var colorRules = []struct{ selector, prop, token string }{
	{"text", "fill", "ink2"},
	{".bg", "fill", "surface"},
	{".t", "fill", "ink1"},
	{".pt", "fill", "ink1"},
	{".v", "fill", "ink1"},
	{".tick", "fill", "muted"},
	{".grid", "stroke", "grid"},
	{".axis", "stroke", "axis"},
	{".lim", "stroke", "ink1"},
	{".mk", "stroke", "surface"},
	{".ho", "fill", "surface"},
	{".halo", "stroke", "surface"},
}

const layoutStyle = `text{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;font-size:12px}` +
	`.t{font-size:16px;font-weight:600}.pt{font-weight:600}.tick{font-variant-numeric:tabular-nums}` +
	`.grid,.axis,.lim{stroke-width:1}.ln{fill:none;stroke-width:2;stroke-linejoin:round;stroke-linecap:round}` +
	`.mk,.ho{stroke-width:2}.halo{stroke-width:4;stroke-linejoin:round;paint-order:stroke}`

// stylesheet is the layout rules plus the color rules for one mode. Each
// slot gets line, filled-marker, hollow-marker and bar classes: .l0 .m0
// .h0 .b0 and so on.
func stylesheet() string {
	color := func(dark bool) string {
		val := map[string]string{}
		for _, t := range tokens {
			val[t.name] = t.light
			if dark {
				val[t.name] = t.dark
			}
		}
		var b strings.Builder
		for _, r := range colorRules {
			fmt.Fprintf(&b, "%s{%s:%s}", r.selector, r.prop, val[r.token])
		}
		for i := range Slots {
			c := val[fmt.Sprintf("s%d", i)]
			fmt.Fprintf(&b, ".l%[1]d,.h%[1]d{stroke:%[2]s}.m%[1]d,.b%[1]d{fill:%[2]s}", i, c)
		}
		return b.String()
	}
	return layoutStyle + color(false) + "@media (prefers-color-scheme:dark){" + color(true) + "}"
}

// doc accumulates one SVG document.
type doc struct {
	b    bytes.Buffer
	w, h float64
}

func newDoc(w, h float64, title, desc, source string) *doc {
	d := &doc{w: w, h: h}
	d.printf(`<svg xmlns="http://www.w3.org/2000/svg" width="%s" height="%s" viewBox="0 0 %s %s" role="img">`+"\n",
		num(w), num(h), num(w), num(h))
	d.printf("<title>%s</title>\n<desc>%s</desc>\n<metadata>%s</metadata>\n", esc(title), esc(desc), esc(source))
	d.printf("<style>%s</style>\n", stylesheet())
	d.printf(`<rect class="bg" width="%s" height="%s"/>`+"\n", num(w), num(h))
	return d
}

func (d *doc) printf(format string, a ...any) { fmt.Fprintf(&d.b, format, a...) }

// text writes a text element; anchor is start, middle or end.
func (d *doc) text(x, y float64, class, anchor, s string) {
	d.printf(`<text x="%s" y="%s"`, num(x), num(y))
	if class != "" {
		d.printf(` class="%s"`, class)
	}
	if anchor != "" && anchor != "start" {
		d.printf(` text-anchor="%s"`, anchor)
	}
	d.printf(">%s</text>\n", esc(s))
}

func (d *doc) line(x1, y1, x2, y2 float64, class string) {
	d.printf(`<line x1="%s" y1="%s" x2="%s" y2="%s" class="%s"/>`+"\n", num(x1), num(y1), num(x2), num(y2), class)
}

// marker is an r=4 dot: filled in the series color with a surface ring, or
// hollow (surface fill, series-color ring). tip is its native tooltip.
func (d *doc) marker(x, y float64, slot int, filled bool, tip string) {
	class := fmt.Sprintf("mk m%d", slot)
	if !filled {
		class = fmt.Sprintf("ho h%d", slot)
	}
	d.printf(`<circle cx="%s" cy="%s" r="4" class="%s"><title>%s</title></circle>`+"\n", num(x), num(y), class, esc(tip))
}

func (d *doc) bytes() []byte {
	d.printf("</svg>\n")
	return d.b.Bytes()
}

// num formats a coordinate with at most one decimal and no trailing zero,
// so output is stable across platforms.
func num(v float64) string {
	s := strconv.FormatFloat(v, 'f', 1, 64)
	s = strings.TrimSuffix(s, ".0")
	if s == "-0" {
		return "0"
	}
	return s
}

func esc(s string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(s)) // strings.Builder never fails
	return b.String()
}

// checkSlot rejects a slot outside the palette.
func checkSlot(name string, slot int) error {
	if slot < 0 || slot >= Slots {
		return fmt.Errorf("series %q: slot %d outside 0–%d", name, slot, Slots-1)
	}
	return nil
}

// Commas formats v with thousands separators and the given decimals:
// Commas(4140.1, 0) = "4,140".
func Commas(v float64, decimals int) string {
	s := strconv.FormatFloat(v, 'f', decimals, 64)
	sign := ""
	if strings.HasPrefix(s, "-") {
		sign, s = "-", s[1:]
	}
	whole, frac, hasFrac := strings.Cut(s, ".")
	var b strings.Builder
	for i, r := range whole {
		if i > 0 && (len(whole)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(r)
	}
	if hasFrac {
		return sign + b.String() + "." + frac
	}
	return sign + b.String()
}
