package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/wrbooth/vllm-serve-bench/internal/chart"
	"github.com/wrbooth/vllm-serve-bench/internal/crosscheck"
	"github.com/wrbooth/vllm-serve-bench/internal/report"
)

// Chart kinds.
const (
	kindLatency  = "latency"
	kindEngine   = "engine"
	kindHeadline = "headline"
)

// seriesSpec names one engine config's series and pins its color, so an
// experiment keeps the same color in every chart whatever else is drawn.
type seriesSpec struct {
	config, name string
	slot         int
}

// seriesFlags is the repeatable --series flag: config[@slot]=Name. Without
// @slot, the slot is the flag's position (the first is the reference).
type seriesFlags []seriesSpec

func (s *seriesFlags) String() string { return strconv.Itoa(len(*s)) }

func (s *seriesFlags) Set(v string) error {
	key, name, ok := strings.Cut(v, "=")
	if !ok || key == "" || name == "" {
		return fmt.Errorf("want config[@slot]=Name, got %q", v)
	}
	spec := seriesSpec{config: key, name: name, slot: len(*s)}
	if cfg, slot, pinned := strings.Cut(key, "@"); pinned {
		n, err := strconv.Atoi(slot)
		if err != nil {
			return fmt.Errorf("%q: slot %q is not a number", v, slot)
		}
		spec.config, spec.slot = cfg, n
	}
	if spec.slot < 0 || spec.slot >= chart.Slots {
		return fmt.Errorf("%q: slot %d outside 0–%d", v, spec.slot, chart.Slots-1)
	}
	*s = append(*s, spec)
	return nil
}

type chartFlags struct {
	kind, out, sloPath, title string
	minUncached               float64
	series                    seriesFlags
}

// chartCmd is `bench chart`: an SVG figure from committed run directories,
// built on the same report tables as docs/03, so a chart and its table
// cannot disagree. The file records the command that made it.
func chartCmd(args []string, stdout, stderr io.Writer) int {
	var f chartFlags
	fset := flag.NewFlagSet("bench chart", flag.ContinueOnError)
	fset.SetOutput(stderr)
	fset.StringVar(&f.kind, "kind", "", "latency (output and SLO percentiles vs concurrency), engine (KV, queue, preemptions) or headline (max compliant goodput)")
	fset.StringVar(&f.out, "out", "", "SVG file to write")
	fset.StringVar(&f.sloPath, "slo", "docs/slo.json", "committed SLO file")
	fset.StringVar(&f.title, "title", "", "chart title (default depends on --kind)")
	fset.Float64Var(&f.minUncached, "min-uncached-fraction", crosscheck.DefaultOptions.MinUncachedFraction,
		"as for bench report: a level under this fraction of its unique prompt part is not compliant")
	fset.Var(&f.series, "series", "config[@slot]=Name, repeatable: series order, display names and colors (slot 0 is the reference)")
	fset.Usage = func() {
		_, _ = fmt.Fprintln(stderr, "usage: bench chart --kind latency|engine|headline --out FILE [--series config=Name]... RUN_DIR...")
		fset.PrintDefaults()
	}
	if err := fset.Parse(args); err != nil {
		return 2
	}
	if f.out == "" || fset.NArg() == 0 || !slices.Contains([]string{kindLatency, kindEngine, kindHeadline}, f.kind) {
		fset.Usage()
		return 2
	}
	command := commandLine(append([]string{"bench", "chart"}, args...))
	if err := writeChart(&f, fset.Args(), command); err != nil {
		_, _ = fmt.Fprintln(stderr, "bench chart:", err)
		return 1
	}
	_, _ = fmt.Fprintln(stdout, "wrote", f.out)
	return 0
}

func writeChart(f *chartFlags, dirs []string, command string) error {
	slo, runs, tables, err := loadTables(f.sloPath, f.minUncached, dirs)
	if err != nil {
		return err
	}
	specs, err := resolveSeries(f.series, tables)
	if err != nil {
		return err
	}
	ids := make([]string, len(runs))
	for i := range runs {
		ids[i] = runs[i].ID()
	}
	source := fmt.Sprintf("Generated by `%s` from %s and %s. Do not edit: rerun the command.",
		command, strings.Join(ids, ", "), f.sloPath)
	svg, err := renderChart(f, &slo, tables, specs, source)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(f.out), 0o755); err != nil { //nolint:gosec // G301: charts are committed and meant to be readable
		return err
	}
	return os.WriteFile(f.out, svg, 0o644) //nolint:gosec // G306: as above
}

func renderChart(f *chartFlags, slo *report.SLO, tables []report.Table, specs []seriesSpec, source string) ([]byte, error) {
	if f.kind == kindHeadline {
		c := headlineChart(tables, specs)
		c.Source = source
		if f.title != "" {
			c.Title = f.title
		}
		return c.SVG()
	}
	profile := tables[0].Profile
	for i := range tables {
		if tables[i].Profile != profile {
			return nil, fmt.Errorf("--kind %s draws one profile; got %s and %s", f.kind, profile, tables[i].Profile)
		}
	}
	p, err := slo.For(profile)
	if err != nil {
		return nil, err
	}
	var c chart.Lines
	if f.kind == kindLatency {
		c = latencyChart(tables, specs, &p)
	} else {
		c = engineChart(tables, specs, &p)
	}
	c.Source = source
	if f.title != "" {
		c.Title = f.title
	}
	return c.SVG()
}

// loadTables loads the SLO and every run, and judges each run's levels.
func loadTables(sloPath string, minUncached float64, dirs []string) (report.SLO, []report.Run, []report.Table, error) {
	slo, err := report.LoadSLO(sloPath)
	if err != nil {
		return report.SLO{}, nil, nil, err
	}
	var runs []report.Run
	var tables []report.Table
	seen := map[string]string{}
	for _, dir := range dirs {
		r, err := report.LoadRun(dir)
		if err != nil {
			return report.SLO{}, nil, nil, err
		}
		if prev, dup := seen[r.ID()]; dup {
			return report.SLO{}, nil, nil, fmt.Errorf("run %s is given twice (%s and %s)", r.ID(), prev, dir)
		}
		seen[r.ID()] = dir
		t, err := report.NewTable(&r, &slo, minUncached)
		if err != nil {
			return report.SLO{}, nil, nil, err
		}
		runs = append(runs, r)
		tables = append(tables, t)
	}
	return slo, runs, tables, nil
}

// resolveSeries returns the series specs in drawing order. With no --series,
// each engine config gets its own series in first-appearance order. With
// --series, every run's config must be listed, and a config drawn twice in
// one profile is an error: one line per config.
func resolveSeries(given seriesFlags, tables []report.Table) ([]seriesSpec, error) {
	specs := slices.Clone([]seriesSpec(given))
	if len(specs) == 0 {
		for i := range tables {
			cfg := tables[i].EngineConfig
			if !slices.ContainsFunc(specs, func(s seriesSpec) bool { return s.config == cfg }) {
				if len(specs) == chart.Slots {
					return nil, fmt.Errorf("more than %d engine configs; name them with --series", chart.Slots)
				}
				specs = append(specs, seriesSpec{config: cfg, name: cfg, slot: len(specs)})
			}
		}
	}
	seen := map[string]bool{}
	for i := range tables {
		t := &tables[i]
		if !slices.ContainsFunc(specs, func(s seriesSpec) bool { return s.config == t.EngineConfig }) {
			return nil, fmt.Errorf("run %s: engine config %q has no --series", t.RunID, t.EngineConfig)
		}
		key := t.Profile + "/" + t.EngineConfig
		if seen[key] {
			return nil, fmt.Errorf("two %s runs of engine config %q; pass one", t.Profile, t.EngineConfig)
		}
		seen[key] = true
	}
	return specs, nil
}

// tableFor returns the profile's table for a config, or nil.
func tableFor(tables []report.Table, profile, config string) *report.Table {
	for i := range tables {
		if tables[i].Profile == profile && tables[i].EngineConfig == config {
			return &tables[i]
		}
	}
	return nil
}

// levelSeries builds one series from a table: y picks the value, ok=false
// skips the level.
func levelSeries(t *report.Table, s seriesSpec, y func(*report.LevelRow) (float64, string, bool)) chart.Series {
	out := chart.Series{Name: s.name, Slot: s.slot}
	for i := range t.Levels {
		l := &t.Levels[i]
		v, text, ok := y(l)
		if !ok {
			continue
		}
		verdict := "misses SLO"
		if l.Compliant() {
			verdict = "meets SLO"
		}
		out.Points = append(out.Points, chart.Point{
			X: float64(l.Level.Concurrency), Y: v, Filled: l.Compliant(),
			Tip: fmt.Sprintf("%s, c=%d: %s, %s", s.name, l.Level.Concurrency, text, verdict),
		})
	}
	return out
}

// xTicks is every concurrency level any table ran.
func xTicks(tables []report.Table) []float64 {
	var out []float64
	for i := range tables {
		for j := range tables[i].Levels {
			c := float64(tables[i].Levels[j].Level.Concurrency)
			if !slices.Contains(out, c) {
				out = append(out, c)
			}
		}
	}
	slices.Sort(out)
	return out
}

// boundPanel is one SLO bound's percentile per level, with the limit line.
// Limits of a second or more are drawn in seconds.
func boundPanel(tables []report.Table, specs []seriesSpec, profile string, bi int, b report.Bound) chart.Panel {
	scale, unit := 1.0, "ms"
	if b.MaxMs >= 1000 {
		scale, unit = 1000, "s"
	}
	metric := fmt.Sprintf("%s p%d", strings.ToUpper(b.Metric), b.Percentile)
	p := chart.Panel{
		Title: metric + " (" + unit + ")",
		Limit: &chart.Limit{Value: b.MaxMs / scale, Label: fmt.Sprintf("SLO ≤ %s %s", chart.Commas(b.MaxMs/scale, 0), unit)},
	}
	for _, s := range specs {
		t := tableFor(tables, profile, s.config)
		if t == nil {
			continue
		}
		p.Series = append(p.Series, levelSeries(t, s, func(l *report.LevelRow) (float64, string, bool) {
			br := l.Bounds[bi]
			v := br.Value / scale
			return v, fmt.Sprintf("%s %s %s", metric, chart.Commas(v, 1), unit), br.HasData
		}))
	}
	return p
}

// sloText is the SLO in words: "TTFT p95 ≤ 100 ms and TPOT p95 ≤ 25 ms".
func sloText(p *report.ProfileSLO) string {
	parts := make([]string, len(p.Bounds))
	for i, b := range p.Bounds {
		v, unit := b.MaxMs, "ms"
		if v >= 1000 {
			v, unit = v/1000, "s"
		}
		parts[i] = fmt.Sprintf("%s p%d ≤ %s %s", strings.ToUpper(b.Metric), b.Percentile, chart.Commas(v, 0), unit)
	}
	return strings.Join(parts, " and ")
}

// latencyChart: output tok/s, then one panel per SLO bound. The tok/s panel
// labels the reference series' headline and the best headline.
func latencyChart(tables []report.Table, specs []seriesSpec, p *report.ProfileSLO) chart.Lines {
	profile := tables[0].Profile
	tok := chart.Panel{Title: "Output tokens/s"}
	for _, s := range specs {
		if t := tableFor(tables, profile, s.config); t != nil {
			tok.Series = append(tok.Series, levelSeries(t, s, func(l *report.LevelRow) (float64, string, bool) {
				return l.Level.OutputTokPerSec, chart.Commas(l.Level.OutputTokPerSec, 1) + " tok/s", true
			}))
		}
	}
	tok.Callouts = headlineCallouts(tables, specs, profile)
	c := chart.Lines{
		Title: titleCase(profile) + " profile: output and tail latency vs concurrency",
		Subtitle: []string{
			"SLO: " + sloText(p) + ". Each point is one 60 s closed-loop level; the prefix cache is reset before each.",
			"Labels mark the highest output at a level that meets the SLO (max compliant goodput).",
		},
		XTitle: "Concurrency (requests in flight, log scale)",
		XTicks: xTicks(tables),
		Key:    true,
		Panels: []chart.Panel{tok},
	}
	for i, b := range p.Bounds {
		c.Panels = append(c.Panels, boundPanel(tables, specs, profile, i, b))
	}
	return c
}

// headlineCallouts labels the first spec's headline and, if different, the
// highest headline. Labelling every series would stack labels where lines
// converge; the legend and docs/03 carry the rest.
func headlineCallouts(tables []report.Table, specs []seriesSpec, profile string) []chart.Callout {
	var ref, best *report.Headline
	var all []report.Headline
	for _, s := range specs {
		t := tableFor(tables, profile, s.config)
		if t == nil {
			continue
		}
		h := report.MaxCompliant(t)
		if !h.Found {
			continue
		}
		all = append(all, h)
	}
	for i := range all {
		if all[i].EngineConfig == specs[0].config {
			ref = &all[i]
		}
		if best == nil || all[i].Best.Level.OutputTokPerSec > best.Best.Level.OutputTokPerSec {
			best = &all[i]
		}
	}
	var out []chart.Callout
	for _, h := range []*report.Headline{ref, best} {
		if h == nil || slices.ContainsFunc(out, func(c chart.Callout) bool {
			return c.X == float64(h.Best.Level.Concurrency) && c.Y == h.Best.Level.OutputTokPerSec
		}) {
			continue
		}
		l := h.Best.Level
		out = append(out, chart.Callout{
			X: float64(l.Concurrency), Y: l.OutputTokPerSec,
			Text: fmt.Sprintf("%s tok/s at c=%d", chart.Commas(l.OutputTokPerSec, 0), l.Concurrency),
		})
	}
	return out
}

// engineChart: what the engine reported inside each level's measured
// window: KV cache use, queued requests, preemptions.
func engineChart(tables []report.Table, specs []seriesSpec, p *report.ProfileSLO) chart.Lines {
	profile := tables[0].Profile
	panel := func(title string, maxY float64, y func(e *report.EngineLevel) (float64, string, bool)) chart.Panel {
		out := chart.Panel{Title: title, Max: maxY}
		for _, s := range specs {
			if t := tableFor(tables, profile, s.config); t != nil {
				out.Series = append(out.Series, levelSeries(t, s, func(l *report.LevelRow) (float64, string, bool) {
					return y(&l.Engine)
				}))
			}
		}
		return out
	}
	return chart.Lines{
		Title: titleCase(profile) + " profile: what the engine reported",
		Subtitle: []string{
			"vLLM /metrics sampled at 1 Hz, restricted to each level's measured window. SLO: " + sloText(p) + ".",
		},
		XTitle: "Concurrency (requests in flight, log scale)",
		XTicks: xTicks(tables),
		Key:    true,
		Panels: []chart.Panel{
			panel("KV cache in use (mean %)", 100, func(e *report.EngineLevel) (float64, string, bool) {
				return e.KV.Mean * 100, "KV " + chart.Commas(e.KV.Mean*100, 1) + "%", e.Samples > 0
			}),
			panel("Requests waiting (mean)", 0, func(e *report.EngineLevel) (float64, string, bool) {
				return e.Waiting.Mean, chart.Commas(e.Waiting.Mean, 1) + " waiting", e.Samples > 0
			}),
			panel("Preemptions in the window", 0, func(e *report.EngineLevel) (float64, string, bool) {
				return e.Preemptions, chart.Commas(e.Preemptions, 0) + " preemptions", e.HasPreemptions
			}),
		},
	}
}

// headlineChart: max compliant goodput per series, one group per profile,
// each with its change against the reference series.
func headlineChart(tables []report.Table, specs []seriesSpec) chart.Bars {
	var profiles []string
	for i := range tables {
		if !slices.Contains(profiles, tables[i].Profile) {
			profiles = append(profiles, tables[i].Profile)
		}
	}
	c := chart.Bars{
		Title: "Max compliant goodput by engine config",
		Subtitle: []string{
			"The highest output tok/s at a concurrency level whose p95s meet the profile's SLO (docs/slo.json),",
			"with the level it was reached at and the change against " + specs[0].name + ".",
		},
	}
	for _, profile := range profiles {
		g := chart.BarGroup{Title: titleCase(profile) + " profile"}
		var ref *report.Headline
		if t := tableFor(tables, profile, specs[0].config); t != nil {
			h := report.MaxCompliant(t)
			ref = &h
		}
		for _, s := range specs {
			t := tableFor(tables, profile, s.config)
			if t == nil {
				continue
			}
			g.Bars = append(g.Bars, headlineBar(report.MaxCompliant(t), ref, s))
		}
		c.Groups = append(c.Groups, g)
	}
	return c
}

func headlineBar(h report.Headline, ref *report.Headline, s seriesSpec) chart.Bar {
	b := chart.Bar{Name: s.name, Slot: s.slot}
	if !h.Found {
		b.Missing, b.Label = true, "no level meets the SLO"
		return b
	}
	l := h.Best.Level
	b.Value = l.OutputTokPerSec
	b.Label = fmt.Sprintf("%s tok/s at c=%d", chart.Commas(l.OutputTokPerSec, 0), l.Concurrency)
	if ref != nil && ref.Found && ref.EngineConfig != h.EngineConfig {
		if d := report.DeltaPct(ref.Best.Level.OutputTokPerSec, l.OutputTokPerSec); d != nil {
			b.Label += fmt.Sprintf(" (%+.1f%%)", *d)
		}
	}
	return b
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
