package main

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/wrbooth/vllm-serve-bench/internal/report"
)

// shellWords splits a command line the way commandLine quotes it: words
// separated by spaces, single quotes grouping, '\” an escaped quote.
func shellWords(t *testing.T, s string) []string {
	t.Helper()
	var words []string
	var cur strings.Builder
	inWord, quoted := false, false
	for i := 0; i < len(s); i++ {
		switch c := s[i]; {
		case quoted && c == '\'':
			quoted = false
		case quoted:
			cur.WriteByte(c)
		case c == '\'':
			quoted, inWord = true, true
		case c == '\\' && i+1 < len(s):
			i++
			cur.WriteByte(s[i])
			inWord = true
		case c == ' ':
			if inWord {
				words, inWord = append(words, cur.String()), false
				cur.Reset()
			}
		default:
			cur.WriteByte(c)
			inWord = true
		}
	}
	if quoted {
		t.Fatalf("unterminated quote in %q", s)
	}
	if inWord {
		words = append(words, cur.String())
	}
	return words
}

func TestShellWordsUndoesCommandLine(t *testing.T) {
	t.Parallel()
	argv := []string{"bench", "chart", "--series", "b2-fp8@1=B2: FP8 weights", "--title", "it's a title", "results/x"}
	if got := shellWords(t, commandLine(argv)); !slices.Equal(got, argv) {
		t.Errorf("round trip gave %q, want %q", got, argv)
	}
}

// chartCommandIn returns the argv recorded in an SVG's <metadata>.
func chartCommandIn(t *testing.T, svg []byte) []string {
	t.Helper()
	_, rest, ok := strings.Cut(string(svg), "<metadata>Generated by `")
	if !ok {
		t.Fatal("no <metadata> records a command")
	}
	cmd, _, _ := strings.Cut(rest, "`")
	for _, ent := range [][2]string{{"&#39;", "'"}, {"&#34;", `"`}, {"&lt;", "<"}, {"&gt;", ">"}, {"&amp;", "&"}} {
		cmd = strings.ReplaceAll(cmd, ent[0], ent[1])
	}
	return shellWords(t, cmd)
}

// Every committed chart is what the command in its <metadata> produces
// from the committed runs, byte for byte, so none can go stale or be
// touched up by hand. Not parallel: t.Chdir.
func TestChartsRegenerateTheCommittedSVGs(t *testing.T) {
	// Absolute, since each chart's regeneration moves the working directory.
	dir, err := filepath.Abs(filepath.Join("..", "..", "docs", "charts"))
	if err != nil {
		t.Fatal(err)
	}
	paths, err := filepath.Glob(filepath.Join(dir, "*.svg"))
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) == 0 {
		t.Fatal("no committed charts in docs/charts")
	}
	for _, p := range paths {
		t.Run(filepath.Base(p), func(t *testing.T) { regenerateChart(t, p) })
	}
}

// regenerateChart reruns the command recorded in one committed chart in a
// scratch root holding its inputs, and compares the output byte for byte.
// Its own subtest, so t.Chdir is undone before the next chart.
func regenerateChart(t *testing.T, p string) {
	t.Helper()
	want, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	argv := chartCommandIn(t, want)
	if len(argv) < 2 || argv[0] != "bench" || argv[1] != "chart" {
		t.Fatalf("%s records %q, not a bench chart command", p, argv)
	}
	root := t.TempDir()
	copyFile(t, root, "docs/slo.json")
	for _, a := range argv {
		if strings.HasPrefix(a, "results/") {
			copyRunDir(t, root, a)
		}
	}
	out := filepath.Join("docs", "charts", filepath.Base(p))
	if !slices.Contains(argv, out) {
		t.Fatalf("%s records a command that writes elsewhere: %q", p, argv)
	}
	t.Chdir(root)
	code, stdout, stderr := runBench(t, argv[1:]...)
	if code != 0 {
		t.Fatalf("exit %d; stdout %q stderr %q", code, stdout, stderr)
	}
	got, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("regenerated %s differs from the committed one; run scripts/charts.sh and commit the result", out)
	}
}

func TestSeriesFlagParsesNamesAndPinnedSlots(t *testing.T) {
	t.Parallel()
	var s seriesFlags
	for _, v := range []string{"baseline=Baseline (bf16)", "b2-fp8@1=B2: FP8=weights", "a-mnbt8192=A"} {
		if err := s.Set(v); err != nil {
			t.Fatalf("Set(%q): %v", v, err)
		}
	}
	want := seriesFlags{
		{config: "baseline", name: "Baseline (bf16)", slot: 0},
		{config: "b2-fp8", name: "B2: FP8=weights", slot: 1},
		{config: "a-mnbt8192", name: "A", slot: 2}, // position, not pinned
	}
	if !slices.Equal(s, want) {
		t.Errorf("parsed %+v, want %+v", s, want)
	}
	if s.String() != "3" {
		t.Errorf("String() = %q", s.String())
	}
	for _, bad := range []string{"noequals", "=Name", "cfg=", "cfg@x=Name", "cfg@4=Name", "cfg@-1=Name"} {
		var f seriesFlags
		if err := f.Set(bad); err == nil {
			t.Errorf("Set(%q) accepted it", bad)
		}
	}
}

func TestResolveSeriesDefaultsToFirstAppearanceAndRejectsUnnamedOrDuplicateConfigs(t *testing.T) {
	t.Parallel()
	tables := []report.Table{
		{RunID: "r1", Profile: "interactive", EngineConfig: "baseline"},
		{RunID: "r2", Profile: "interactive", EngineConfig: "b2-fp8"},
		{RunID: "r3", Profile: "throughput", EngineConfig: "baseline"},
	}
	got, err := resolveSeries(nil, tables)
	if err != nil {
		t.Fatal(err)
	}
	want := []seriesSpec{{"baseline", "baseline", 0}, {"b2-fp8", "b2-fp8", 1}}
	if !slices.Equal(got, want) {
		t.Errorf("default series %+v, want %+v", got, want)
	}

	if _, err := resolveSeries(seriesFlags{{config: "baseline", name: "B"}}, tables); err == nil ||
		!strings.Contains(err.Error(), `"b2-fp8" has no --series`) {
		t.Errorf("an unnamed config: err = %v", err)
	}
	dup := append(slices.Clone(tables), report.Table{RunID: "r4", Profile: "interactive", EngineConfig: "baseline"})
	if _, err := resolveSeries(nil, dup); err == nil || !strings.Contains(err.Error(), "two interactive runs") {
		t.Errorf("two runs of one config in one profile: err = %v", err)
	}
	many := []report.Table{}
	for _, c := range []string{"a", "b", "c", "d", "e"} {
		many = append(many, report.Table{RunID: c, Profile: "interactive", EngineConfig: c})
	}
	if _, err := resolveSeries(nil, many); err == nil || !strings.Contains(err.Error(), "more than 4") {
		t.Errorf("five configs without --series: err = %v", err)
	}
}

func TestChartUsageErrorsExitTwo(t *testing.T) {
	t.Parallel()
	for _, args := range [][]string{
		{"chart"},
		{"chart", "--kind", "latency", tpRun},               // no --out
		{"chart", "--out", "x.svg", tpRun},                  // no --kind
		{"chart", "--kind", "pie", "--out", "x.svg", tpRun}, // unknown kind
		{"chart", "--kind", "latency", "--out", "x.svg"},    // no runs
		{"chart", "--nope"},
	} {
		if code, _, _ := runBench(t, args...); code != 2 {
			t.Errorf("%q: exit %d, want 2", args, code)
		}
	}
}

func TestChartFailsOnABadRunOrSLO(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	out := filepath.Join(t.TempDir(), "c.svg")
	if code, _, stderr := runBench(t, "chart", "--kind", "latency", "--out", out,
		"--slo", filepath.Join(root, "missing.json"), filepath.Join(root, tpRun)); code != 1 || stderr == "" {
		t.Errorf("a missing SLO file: exit %d, stderr %q", code, stderr)
	}
	if code, _, _ := runBench(t, "chart", "--kind", "latency", "--out", out,
		"--slo", filepath.Join(root, "docs", "slo.json"), filepath.Join(root, "results", "none")); code != 1 {
		t.Errorf("a missing run: exit %d, want 1", code)
	}
	run := filepath.Join(root, tpRun)
	if code, _, stderr := runBench(t, "chart", "--kind", "latency", "--out", out,
		"--slo", filepath.Join(root, "docs", "slo.json"), run, run); code != 1 || !strings.Contains(stderr, "given twice") {
		t.Errorf("a run given twice: exit %d, stderr %q", code, stderr)
	}
}

// Each kind writes an SVG from a committed run, with the given title, and
// the engine and headline kinds carry their panels and labels.
func TestChartWritesEachKind(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	slo := filepath.Join(root, "docs", "slo.json")
	run := filepath.Join(root, tpRun)
	for kind, want := range map[string][]string{
		kindLatency:  {"Output tokens/s", "E2E p95 (s)", "SLO ≤ 15 s", "1,584 tok/s at c=64", "My title"},
		kindEngine:   {"KV cache in use (mean %)", "Requests waiting (mean)", "Preemptions in the window"},
		kindHeadline: {"Throughput profile", "1,584 tok/s at c=64", "Max compliant goodput"},
	} {
		out := filepath.Join(t.TempDir(), kind+".svg")
		args := []string{"chart", "--kind", kind, "--out", out, "--slo", slo, "--series", "baseline=Base"}
		if kind == kindLatency {
			args = append(args, "--title", "My title")
		}
		code, stdout, stderr := runBench(t, append(args, run)...)
		if code != 0 {
			t.Fatalf("%s: exit %d, stderr %q", kind, code, stderr)
		}
		if !strings.Contains(stdout, "wrote "+out) {
			t.Errorf("%s: stdout %q", kind, stdout)
		}
		b, err := os.ReadFile(out)
		if err != nil {
			t.Fatal(err)
		}
		for _, w := range want {
			if !strings.Contains(string(b), w) {
				t.Errorf("%s chart lacks %q", kind, w)
			}
		}
	}
}

func TestLineChartsRejectTwoProfiles(t *testing.T) {
	t.Parallel()
	slo := report.SLO{}
	tables := []report.Table{{Profile: "interactive"}, {Profile: "throughput"}}
	for _, kind := range []string{kindLatency, kindEngine} {
		if _, err := renderChart(&chartFlags{kind: kind}, &slo, tables, nil, ""); err == nil ||
			!strings.Contains(err.Error(), "draws one profile") {
			t.Errorf("%s: err = %v", kind, err)
		}
	}
}

func TestHeadlineBarSaysSoWhenNoLevelMeetsTheSLO(t *testing.T) {
	t.Parallel()
	b := headlineBar(report.Headline{EngineConfig: "x"}, nil, seriesSpec{config: "x", name: "X", slot: 2})
	if !b.Missing || b.Label != "no level meets the SLO" || b.Slot != 2 {
		t.Errorf("got %+v", b)
	}
}

func TestSLOTextNamesEveryBoundInItsUnit(t *testing.T) {
	t.Parallel()
	p := report.ProfileSLO{Bounds: []report.Bound{
		{Metric: "ttft", Percentile: 95, MaxMs: 100},
		{Metric: "e2e", Percentile: 99, MaxMs: 15000},
	}}
	if got, want := sloText(&p), "TTFT p95 ≤ 100 ms and E2E p99 ≤ 15 s"; got != want {
		t.Errorf("sloText = %q, want %q", got, want)
	}
	if titleCase("") != "" || titleCase("throughput") != "Throughput" {
		t.Error("titleCase")
	}
}
