package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const resultsDoc = "docs/03-results.md"

// copyFile copies a repo-relative file into root at the same path.
func copyFile(t *testing.T, root, rel string) {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", rel))
	if err != nil {
		t.Fatal(err)
	}
	dst := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(dst, b, 0o644); err != nil {
		t.Fatal(err)
	}
}

// copyRunDir copies a committed run directory's files into root.
func copyRunDir(t *testing.T, root, rel string) {
	t.Helper()
	for _, name := range []string{"config.json", "summary.json", "requests.jsonl", "vllm_metrics.csv", "gpu.csv"} {
		copyFile(t, root, filepath.Join(rel, name))
	}
}

// reportCommandIn returns the `bench report` command the document's
// generated blocks record (they all record the same one).
func reportCommandIn(t *testing.T, md []byte) []string {
	t.Helper()
	_, rest, ok := strings.Cut(string(md), "<!-- Generated by `bench report ")
	if !ok {
		t.Fatal("no generated block records a `bench report` command")
	}
	cmd, _, _ := strings.Cut(rest, "`")
	return strings.Fields(cmd)
}

// The committed docs/03-results.md is what the command in its blocks
// produces from the committed run directories, byte for byte: no number
// in it was typed by hand or left stale. The inputs are copied to a
// scratch root so the rewrite never touches the repo. Not parallel:
// t.Chdir.
func TestReportRegeneratesTheCommittedResultsDocument(t *testing.T) {
	want, err := os.ReadFile(filepath.Join("..", "..", resultsDoc))
	if err != nil {
		t.Fatal(err)
	}
	args := reportCommandIn(t, want)
	root := t.TempDir()
	copyFile(t, root, resultsDoc)
	copyFile(t, root, "docs/slo.json")
	for _, a := range args {
		if strings.HasPrefix(a, "results/") {
			copyRunDir(t, root, a)
		}
	}
	t.Chdir(root)

	code, out, errs := runBench(t, append([]string{"report"}, args...)...)
	if code != 0 {
		t.Fatalf("exit %d; stdout %q stderr %q", code, out, errs)
	}
	got, err := os.ReadFile(resultsDoc)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("regenerated %s differs from the committed one; rerun the command in its blocks and commit the result", resultsDoc)
	}
}

// fixtureRoot is a scratch root holding the committed SLO and the
// throughput baseline, the smaller of the two runs.
const tpRun = "results/baseline/throughput-baseline-20260928-014014"

func fixtureRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	copyFile(t, root, "docs/slo.json")
	copyRunDir(t, root, tpRun)
	return root
}

func TestReportStartsAMissingDocumentFromASkeleton(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	out := filepath.Join(root, "new", "03.md")
	code, stdout, errs := runBench(t, "report", "--out", out, "--slo", filepath.Join(root, "docs", "slo.json"), filepath.Join(root, tpRun))
	if code != 0 || !strings.Contains(stdout, "wrote "+out) || errs != "" {
		t.Fatalf("exit %d; stdout %q stderr %q", code, stdout, errs)
	}
	md, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	for _, id := range []string{"slo", "headline:throughput", "table:throughput-baseline-20260928-014014", "engine:throughput-baseline-20260928-014014"} {
		if !bytes.Contains(md, []byte("<!-- bench-report:begin "+id+" -->\n<!-- Generated by `bench report --out ")) {
			t.Errorf("skeleton lacks a filled %s block", id)
		}
	}
}

func TestReportNamesRunsGivenButShownNowhere(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	out := filepath.Join(root, "03.md")
	prose := "# Results\n\nNo blocks yet.\n"
	if err := os.WriteFile(out, []byte(prose), 0o644); err != nil {
		t.Fatal(err)
	}
	code, _, errs := runBench(t, "report", "--out", out, "--slo", filepath.Join(root, "docs", "slo.json"), filepath.Join(root, tpRun))
	want := "<!-- bench-report:begin table:throughput-baseline-20260928-014014 -->"
	if code != 0 || !strings.Contains(errs, "has no table block") || !strings.Contains(errs, want) {
		t.Errorf("exit %d, stderr %q; want 0 and a note with the marker to add", code, errs)
	}
	if md, _ := os.ReadFile(out); string(md) != prose {
		t.Errorf("a document without blocks must come back unchanged, got %q", md)
	}
}

func TestReportFailsWithoutWritingOnBadInput(t *testing.T) {
	t.Parallel()
	root := fixtureRoot(t)
	slo, run := filepath.Join(root, "docs", "slo.json"), filepath.Join(root, tpRun)
	broken := "keep me\n<!-- bench-report:begin table:nope -->\n<!-- bench-report:end table:nope -->\n"
	tests := []struct {
		name string
		args []string
		doc  string
		code int
		want string
	}{
		{"NoRuns", []string{"--slo", slo}, "", 2, "usage"},
		{"UnknownFlag", []string{"--nope"}, "", 2, ""},
		{"NoSLO", []string{"--slo", filepath.Join(root, "absent.json"), run}, "", 1, "absent.json"},
		{"MissingRun", []string{"--slo", slo, filepath.Join(root, "absent")}, "", 1, "absent"},
		{"RunTwice", []string{"--slo", slo, run, run}, "", 1, "given twice"},
		{"UnknownRunInBlock", []string{"--slo", slo, run}, broken, 1, "run nope is not among"},
		{"UnclosedBlock", []string{"--slo", slo, run}, "<!-- bench-report:begin slo -->\n", 1, "no end marker"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			out := filepath.Join(t.TempDir(), "03.md")
			if tt.doc != "" {
				if err := os.WriteFile(out, []byte(tt.doc), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			code, _, errs := runBench(t, append([]string{"report", "--out", out}, tt.args...)...)
			if code != tt.code || !strings.Contains(errs, tt.want) {
				t.Errorf("exit %d, stderr %q; want %d and %q", code, errs, tt.code, tt.want)
			}
			md, err := os.ReadFile(out)
			switch {
			case tt.doc == "" && err == nil:
				t.Errorf("a failed run created %s", out)
			case tt.doc != "" && string(md) != tt.doc:
				t.Errorf("a failed run changed the document to %q", md)
			}
		})
	}
}
